#!/bin/bash

function inform() {
	clear
	echo $1
}

function reboot() {
	shutdown -r 0
}

function changeShell() {
	chsh -s /bin/zsh $(logname)
}

function getPowerLineFonts() {
	inform "Installing powerline fonts"
	git clone git@github.com:powerline/fonts.git
	bash fonts/install.sh
	rm -rf fonts
}

function getOtherSw() {
	inform "Installing other software"
	# Chrome
	curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
	dpkg -i google-chrome-stable_current_amd64.deb
	rm  google-chrome-stable_current_amd64.deb

	# Skype
	curl -O http://download.skype.com/linux/skype-ubuntu-precise_4.3.0.37-1_i386.deb
	dpkg -i skype-ubuntu-precise_4.3.0.37-1_i386.deb
	rm skype-ubuntu-precise_4.3.0.37-1_i386.deb

	# Tmux
	curl -O \|https://github.com/tmux/tmux/releases/download/2.0/tmux-2.0.tar.gz
	tar -xvf tmux-2.0.tar.gz
	tmux-2.0/make
	tmux-2.0/make install
	rm tmux-2.0
}

function mkSSHKeys() {
	inform "Generating ssh key pair"
	bash ~/Scripts/ssh_keygen
}

function getLatestPy2Py3() {
	inform "Installing python 2.7.10 and 3.4.3"
	pyenv install 2.7.10
	PYENV_VERSION=2.7.10 pip install virtualenvwrapper
	pyenv install 3.4.3
	PYENV_VERSION=3.4.3 pip install virtualenvwrapper
}

function getPythonSw() {
	inform "Installing python software"
	pip install virtualenvwrapper
	pip install pyenv
}

function getPip() {
	inform "Curling and installing get-pip.py"
	curl -O https://bootstrap.pypa.io/get-pip.py
	python get-pip.py
	rm get-pip.py
}

function getLibsAndSwFromAptitude() {
	inform "Installing libraries and software"
	while IFS='' read -r pkg || [[ -n $pkg ]]; do
		apt-get install -y $pkg
	done < ~/.pkgs
}

function mkSymlinks() {
	inform "Making symbolic links to the home folder"
	for sl in ~/.dotfiles/*.symlink do
		eval "ln -s $sl ~/.$sl"
		source ~/".$sl"
	done
}

function getDotfiles() {
	inform "Cloning dotfiles"
	git clone git@github.com:ewilazarus/dotfiles.git ~/.dotfiles --recursive && chown -R $(logname) ~/.dotfiles
}

function mkDirs() {
	inform "Creating directory structure"
	mkdir ~/Lab && chown -R $(logname) ~/Lab
	mkdir ~/Workspace && chown -R $(logname) ~/Workspace
	git clone git@github.com:ewilazarus/scripts.git ~/Scripts && chown -R $(logname) ~/Scripts
}

function getGit() {
	inform "Installing git"
	apt-get install -y git
}

function addExtraOficialAptitudeRepositories() {
	inform "Adding extra-official aptitude repositories"
	apt-add-repository ppa:numix/ppa
}

function updUpg() {
	inform "Updating and upgrading packages"
	addExtraOficialAptitudeRepositories()
	apt-get update
	apt-get upgrade
}

function main() {
	updUpg()
	getGit()
	mkDirs()
	getDotfiles()
	mkSymlinks()
	getLibsAndSwFromAptitude()
	getPip()
	getPythonSw()
	getLatestPy2Py3()
	mkSSHKeys()
	getOtherSw()
	getPowerLineFonts()
	changeShell()
	reboot()
}

main()
